### ISSUE TITLE
Celery.task types loose type information

### ISSUE THREAD

**Issue by sk-** [sbdchd/celery-types#223]
The types of [Celery.task](https://github.com/sbdchd/celery-types/blob/e2af3ae85b94a07942ffd5c0a5daf434be85343f/celery-stubs/app/base.pyi#L195-L356) loose type information because they return a [_T_Global](https://github.com/sbdchd/celery-types/blob/e2af3ae85b94a07942ffd5c0a5daf434be85343f/celery-stubs/app/base.pyi#L42-L46) in some cases. This is different to how [shared_task](https://github.com/sbdchd/celery-types/blob/e2af3ae85b94a07942ffd5c0a5daf434be85343f/celery-stubs/app/__init__.pyi#L64-L225) is typed.

The code below shows how the type information is lost:

```python
from typing import reveal_type

import celery

celery_app = celery.Celery()

@celery_app.task()
def task1(a: int) -> int:
    return a

@celery.shared_task()
def task2(a: int) -> int:
    return a

reveal_type(task1)
reveal_type(task2)
```

Mypy, pyright show these types:

```
tasks2.py:15: note: Revealed type is "celery.app.task.Task[Any, Any]"
tasks2.py:16: note: Revealed type is "celery.app.task.Task[[a: int], int]"
```

**Comment by sk-** [comment]
This seems to have been broken by https://github.com/sbdchd/celery-types/pull/203. @sbdchd WDYT?

**Comment by sk-** [comment]
This issue is also affecting [zuban](https://github.com/zubanls/zuban), making it generate errors like:

```
test.py:7: error: Argument 1 has incompatible type "Callable[[int], int]"; expected "Callable[_P, _R]"  [arg-type]
Found 1 errors in 1 file (checked 1 source file)
```

I used the same python code above with two extra `delay` calls.

```python
from typing import reveal_type

import celery

celery_app = celery.Celery()

@celery_app.task()
def task1(a: int) -> int:
    return a

@celery.shared_task()
def task2(a: int) -> int:
    return a

reveal_type(task1)
reveal_type(task2)

task1.delay(3)
task2.delay(3)
```

**Comment by sbdchd** [comment]
Yeah I'm fine if we revert that PR, ideally celery types are easy to drop in with existing code
